[package]
name = "vectorscan-rs-example"
description = "Example binary that statically links vectorscan-rs"
publish = false

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
vectorscan-rs = { version = "0.0.5", path = "../vectorscan-rs" }
